# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DIVINESPEAR'S LIBRARIUM SANCTORUM
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Knowledge is power, Guard it well. <strike>Wargear is power, Steal it well.</strike>
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
show_excerpts: true

# Build settings
timezone: Asia/Seoul
markdown: kramdown
#theme: minima
remote_theme: thelehhman/plainwhite-jekyll
plugins:
  - jekyll-feed

# Theme settings
plainwhite:
  name: Divinespear
  tagline: Knowledge is power, Guard it well.<br/><strike>Wargear is power, Steal it well.</strike>
  date_format: "%Y-%m-%d"
  social_links:
    #twitter: thelehhman
    #linkedIn: in/thelehhman # format: locale/username
    github: divinespear
    facebook: divinespear
    instagram: divinespear.kang
  sitemap: true
  disqus_shortname: "divinespear-github-io"
  analytics_id: "UA-40211319-4"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
